"""Declarative base and shared column type helpers.

This module — and everything under adapters/db/ — is I/O and framework code by definition
(SQLAlchemy), so it lives in adapters/, never domain/. That boundary is enforced by the
import-linter contract in pyproject.toml, not just documented here.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import MetaData
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, mapped_column

# Naming convention makes autogenerated Alembic constraint names stable and greppable —
# without it, Alembic invents names like `ix_1234` that are meaningless in a migration diff.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk():
    """Standard UUID primary key. Postgres side generates v4 via gen_random_uuid();
    v7 (time-ordered) is a documented future upgrade once the pg_uuidv7 extension is
    confirmed available in the target Postgres 16 image — not blocking for MVP."""
    return mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


def utc_now_column(nullable: bool = False):
    from sqlalchemy import DateTime, func

    return mapped_column(DateTime(timezone=True), nullable=nullable, server_default=func.now())


UUIDType = PG_UUID(as_uuid=True)
TimestampType = datetime
