"""initial schema

Revision ID: 71fc580c5fd8
Revises:
Create Date: 2026-08-25 08:09:46.261510

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "71fc580c5fd8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_card",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column(
            "instrument",
            sa.Enum(
                "upi", "card_debit", "card_credit", "netbanking", "wallet", "emi", name="instrument"
            ),
            nullable=False,
        ),
        sa.Column("min_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("max_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("percent_bps", sa.Integer(), nullable=False),
        sa.Column("flat_fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax_percent_bps", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_card")),
        sa.UniqueConstraint(
            "version", "instrument", "min_amount", name="uq_rate_card_version_instrument_min"
        ),
    )
    op.create_table(
        "ruleset",
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_ruleset")),
    )
    op.create_table(
        "schema_mapping",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("orders", "gateway_settlement", "bank_statement", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("header_fingerprint", sa.CHAR(length=64), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "method",
            sa.Enum("deterministic", "cached", "llm", "human", name="mappingmethod"),
            nullable=False,
        ),
        sa.Column("confirmed_by_human", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_mapping")),
        sa.UniqueConstraint(
            "source_type", "header_fingerprint", name="uq_schema_mapping_source_fingerprint"
        ),
    )
    op.create_table(
        "recon_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "awaiting_review",
                "completed",
                "failed",
                "cancelled",
                name="runstatus",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("orchestrator_state", sa.Text(), nullable=False),
        sa.Column("ruleset_version", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("rng_seed", sa.Integer(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("input_manifest_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("llm_mode", sa.String(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_recon_run_period_end_after_start")
        ),
        sa.ForeignKeyConstraint(
            ["ruleset_version"],
            ["ruleset.version"],
            name=op.f("fk_recon_run_ruleset_version_ruleset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recon_run")),
        sa.UniqueConstraint(
            "input_manifest_hash", "ruleset_version", name="uq_recon_run_manifest_ruleset"
        ),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("hash", sa.CHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["recon_run.id"], name=op.f("fk_audit_log_run_id_recon_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "data_source_file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("orders", "gateway_settlement", "bank_statement", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("schema_mapping_id", sa.UUID(), nullable=True),
        sa.Column("mapping_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_data_source_file_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schema_mapping_id"],
            ["schema_mapping.id"],
            name=op.f("fk_data_source_file_schema_mapping_id_schema_mapping"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source_file")),
        sa.UniqueConstraint("run_id", "source_type", name="uq_data_source_file_run_source"),
    )
    op.create_table(
        "eval_metric",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("metric_name", sa.Text(), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("is_baseline", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_eval_metric_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_metric")),
        sa.UniqueConstraint(
            "run_id", "metric_name", "is_baseline", name="uq_eval_metric_run_name_baseline"
        ),
    )
    op.create_index(op.f("ix_eval_metric_run_id"), "eval_metric", ["run_id"], unique=False)
    op.create_table(
        "ground_truth_link",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type_a",
            sa.Enum("order", "settlement_line", "bank_txn", name="entitytype"),
            nullable=False,
        ),
        sa.Column("entity_id_a", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type_b",
            sa.Enum("order", "settlement_line", "bank_txn", name="entitytype"),
            nullable=False,
        ),
        sa.Column("entity_id_b", sa.UUID(), nullable=False),
        sa.Column("expected_allocated_amount", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("pathology", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_ground_truth_link_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ground_truth_link")),
    )
    op.create_index(
        op.f("ix_ground_truth_link_run_id"), "ground_truth_link", ["run_id"], unique=False
    )
    op.create_table(
        "llm_call",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "purpose", sa.Enum("schema_map", "triage", "explain", name="llmpurpose"), nullable=False
        ),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("prompt_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("was_cached", sa.Boolean(), nullable=False),
        sa.Column("validation_attempts", sa.SmallInteger(), nullable=False),
        sa.Column("validation_failed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_llm_call_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_call")),
    )
    op.create_index(op.f("ix_llm_call_run_id"), "llm_call", ["run_id"], unique=False)
    op.create_table(
        "match_group",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("T1_PAYMENT_ID", "T2_UTR", "T3_ALLOCATION", "T4_FEE", name="matchtier"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "status",
            sa.Enum("auto_confirmed", "pending_review", "approved", "rejected", name="matchstatus"),
            nullable=False,
        ),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("ruleset_version", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ruleset_version"],
            ["ruleset.version"],
            name=op.f("fk_match_group_ruleset_version_ruleset"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_match_group_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_group")),
    )
    op.create_index(op.f("ix_match_group_run_id"), "match_group", ["run_id"], unique=False)
    op.create_table(
        "bank_txn",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("utr_extracted", sa.Text(), nullable=True),
        sa.Column("credit", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("debit", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("balance", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("row_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("injected_pathology", sa.Text(), nullable=True),
        sa.CheckConstraint("credit = 0 OR debit = 0", name=op.f("ck_bank_txn_credit_xor_debit")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_bank_txn_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["data_source_file.id"],
            name=op.f("fk_bank_txn_source_file_id_data_source_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_txn")),
        sa.UniqueConstraint("run_id", "row_hash", name="uq_bank_txn_run_row_hash"),
    )
    op.create_index(op.f("ix_bank_txn_run_id"), "bank_txn", ["run_id"], unique=False)
    op.create_index(op.f("ix_bank_txn_utr_extracted"), "bank_txn", ["utr_extracted"], unique=False)
    op.create_index(op.f("ix_bank_txn_value_date"), "bank_txn", ["value_date"], unique=False)
    op.create_table(
        "exception_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "missing_in_bank",
                "missing_in_gateway",
                "orphan_bank_credit",
                "amount_mismatch",
                "fee_variance",
                "duplicate_utr",
                "partial_settlement",
                "period_boundary_timing",
                "netted_refund_unlinked",
                "chargeback_debit_unlinked",
                "unknown_adjustment",
                "ambiguous_multi_candidate",
                name="exceptioncategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum("order", "settlement_line", "bank_txn", name="entitytype"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("amount_at_risk", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("deterministic_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column(
            "proposed_action",
            sa.Enum(
                "propose_match",
                "propose_split_allocation",
                "flag_fee_variance",
                "flag_missing_in_bank",
                "request_more_data",
                "escalate_to_human",
                name="proposedaction",
            ),
            nullable=True,
        ),
        sa.Column("action_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("llm_call_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open", "approved", "rejected", "escalated", "auto_resolved", name="exceptionstatus"
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("reject_reason_code", sa.Text(), nullable=True),
        sa.Column("resolved_match_group_id", sa.UUID(), nullable=True),
        sa.Column("resolved_by", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'rejected' OR reject_reason_code IS NOT NULL",
            name=op.f("ck_exception_item_rejected_requires_reason_code"),
        ),
        sa.ForeignKeyConstraint(
            ["llm_call_id"], ["llm_call.id"], name=op.f("fk_exception_item_llm_call_id_llm_call")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_match_group_id"],
            ["match_group.id"],
            name=op.f("fk_exception_item_resolved_match_group_id_match_group"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_exception_item_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exception_item")),
    )
    op.create_index(op.f("ix_exception_item_run_id"), "exception_item", ["run_id"], unique=False)
    op.create_table(
        "match_member",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("order", "settlement_line", "bank_txn", name="entitytype"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["match_group.id"],
            name=op.f("fk_match_member_group_id_match_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_member")),
    )
    op.create_table(
        "order_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("invoice_no", sa.Text(), nullable=True),
        sa.Column("customer_ref", sa.Text(), nullable=True),
        sa.Column("gross", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("payment_id", sa.Text(), nullable=True),
        sa.Column("order_status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("injected_pathology", sa.Text(), nullable=True),
        sa.CheckConstraint("gross >= 0", name=op.f("ck_order_record_gross_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_order_record_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["data_source_file.id"],
            name=op.f("fk_order_record_source_file_id_data_source_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_record")),
        sa.UniqueConstraint("run_id", "row_hash", name="uq_order_record_run_row_hash"),
    )
    op.create_index(
        op.f("ix_order_record_payment_id"), "order_record", ["payment_id"], unique=False
    )
    op.create_index(op.f("ix_order_record_run_id"), "order_record", ["run_id"], unique=False)
    op.create_table(
        "settlement_line",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=False),
        sa.Column("settlement_id", sa.Text(), nullable=False),
        sa.Column("payment_id", sa.Text(), nullable=True),
        sa.Column("order_ref", sa.Text(), nullable=True),
        sa.Column(
            "line_type",
            sa.Enum("payment", "refund", "chargeback", "adjustment", "reversal", name="linetype"),
            nullable=False,
        ),
        sa.Column("gross", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("net", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "instrument",
            sa.Enum(
                "upi", "card_debit", "card_credit", "netbanking", "wallet", "emi", name="instrument"
            ),
            nullable=True,
        ),
        sa.Column("settled_on", sa.Date(), nullable=False),
        sa.Column("utr", sa.Text(), nullable=True),
        sa.Column("row_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("injected_pathology", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "line_type <> 'payment' OR net = gross - fee - tax",
            name=op.f("ck_settlement_line_net_equals_gross_minus_fee_tax_for_payment_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_settlement_line_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["data_source_file.id"],
            name=op.f("fk_settlement_line_source_file_id_data_source_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_line")),
        sa.UniqueConstraint("run_id", "row_hash", name="uq_settlement_line_run_row_hash"),
    )
    op.create_index(
        op.f("ix_settlement_line_payment_id"), "settlement_line", ["payment_id"], unique=False
    )
    op.create_index(op.f("ix_settlement_line_run_id"), "settlement_line", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_settlement_line_settlement_id"), "settlement_line", ["settlement_id"], unique=False
    )
    op.create_index(op.f("ix_settlement_line_utr"), "settlement_line", ["utr"], unique=False)
    op.create_table(
        "fee_variance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("settlement_line_id", sa.UUID(), nullable=False),
        sa.Column("expected_fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("expected_tax", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("reported_fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("reported_tax", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("delta", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("rate_card_version", sa.Text(), nullable=False),
        sa.Column("within_tolerance", sa.Boolean(), nullable=False),
        sa.Column(
            "instrument_resolved",
            sa.Enum(
                "upi", "card_debit", "card_credit", "netbanking", "wallet", "emi", name="instrument"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["recon_run.id"],
            name=op.f("fk_fee_variance_run_id_recon_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["settlement_line_id"],
            ["settlement_line.id"],
            name=op.f("fk_fee_variance_settlement_line_id_settlement_line"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_variance")),
        sa.UniqueConstraint("settlement_line_id", name=op.f("uq_fee_variance_settlement_line_id")),
    )
    op.create_index(op.f("ix_fee_variance_run_id"), "fee_variance", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fee_variance_run_id"), table_name="fee_variance")
    op.drop_table("fee_variance")
    op.drop_index(op.f("ix_settlement_line_utr"), table_name="settlement_line")
    op.drop_index(op.f("ix_settlement_line_settlement_id"), table_name="settlement_line")
    op.drop_index(op.f("ix_settlement_line_run_id"), table_name="settlement_line")
    op.drop_index(op.f("ix_settlement_line_payment_id"), table_name="settlement_line")
    op.drop_table("settlement_line")
    op.drop_index(op.f("ix_order_record_run_id"), table_name="order_record")
    op.drop_index(op.f("ix_order_record_payment_id"), table_name="order_record")
    op.drop_table("order_record")
    op.drop_table("match_member")
    op.drop_index(op.f("ix_exception_item_run_id"), table_name="exception_item")
    op.drop_table("exception_item")
    op.drop_index(op.f("ix_bank_txn_value_date"), table_name="bank_txn")
    op.drop_index(op.f("ix_bank_txn_utr_extracted"), table_name="bank_txn")
    op.drop_index(op.f("ix_bank_txn_run_id"), table_name="bank_txn")
    op.drop_table("bank_txn")
    op.drop_index(op.f("ix_match_group_run_id"), table_name="match_group")
    op.drop_table("match_group")
    op.drop_index(op.f("ix_llm_call_run_id"), table_name="llm_call")
    op.drop_table("llm_call")
    op.drop_index(op.f("ix_ground_truth_link_run_id"), table_name="ground_truth_link")
    op.drop_table("ground_truth_link")
    op.drop_index(op.f("ix_eval_metric_run_id"), table_name="eval_metric")
    op.drop_table("eval_metric")
    op.drop_table("data_source_file")
    op.drop_table("audit_log")
    op.drop_table("recon_run")
    op.drop_table("schema_mapping")
    op.drop_table("ruleset")
    op.drop_table("rate_card")
    # ### end Alembic commands ###
